// Prerequisite graph for the UWA handbook.
//
// Data is generated by scripts/handbook/parse.mjs into public/uwa-units/.
// graph.json holds every unit with its rule text; the heavier prose is split
// per subject prefix and only fetched when a unit is actually selected.

import cytoscape from "cytoscape";
import dagre from "cytoscape-dagre";

cytoscape.use(dagre);

// ------------------------------------------------------------------ types

interface Rule {
  html: string;
  units: string[];
}

type RuleKind =
  "prerequisites" | "corequisites" | "incompatibility" | "advisable" | "quota";

interface Unit {
  code: string;
  title: string;
  subject: string;
  credits: number | null;
  level: number | null;
  levelOfStudy: string;
  school: string;
  availability: string[];
  rules?: Partial<Record<RuleKind, Rule>>;
  prereqUnits?: string[];
  coreqUnits?: string[];
  incompatibleUnits?: string[];
  advisableUnits?: string[];
}

interface MajorGroup {
  label: string;
  take: string;
  kind: "core" | "option";
  units: { code: string; availability: string; requirements: string }[];
}

interface Major {
  code: string;
  name: string;
  kind: "major" | "disambiguation";
  levels: { level: string; groups: MajorGroup[] }[];
  variants: string[];
}

interface UnitDetail {
  description: string;
  outcomes: string;
  assessment: string;
  contactHours: string;
  coordinators: string;
}

type Membership = "core" | "option" | "outside";

// ------------------------------------------------------------- dom helpers

const el = <T extends HTMLElement>(id: string) =>
  document.getElementById(id) as T;

const $status = el<HTMLDivElement>("status");
const $workspace = el<HTMLElement>("workspace");
const $compact = el<HTMLElement>("compact");
const $compactList = el<HTMLDivElement>("compact-list");
const $detail = el<HTMLElement>("detail");
const $major = el<HTMLSelectElement>("major");
const $search = el<HTMLInputElement>("unit-search");
const $options = el<HTMLDataListElement>("unit-options");
const $outside = el<HTMLInputElement>("include-outside");
const $advisable = el<HTMLInputElement>("include-advisable");
const $overlay = el<HTMLDivElement>("overlay");
const $provenance = el<HTMLSpanElement>("provenance");

const BASE = import.meta.env.BASE_URL;
const HANDBOOK = "https://www.handbooks.uwa.edu.au";

/** Escape anything that came from the handbook before it goes into innerHTML. */
function esc(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function note(kind: "info" | "error", body: string) {
  const border = kind === "error" ? "var(--tag-warn-fg)" : "var(--line)";
  $status.innerHTML = `<div class="rounded-[var(--radius-card)] border bg-surface p-4 text-sm text-ink-soft" style="border-color:${border}">${body}</div>`;
}

function clearNote() {
  $status.innerHTML = "";
}

/** Skeleton that matches the real layout rather than a spinner. */
function showSkeleton() {
  $status.innerHTML = `
    <div class="animate-pulse rounded-[var(--radius-card)] border border-line bg-surface p-5">
      <div class="h-3 w-40 rounded bg-surface-tint"></div>
      <div class="mt-6 grid gap-3">
        <div class="h-24 rounded-[var(--radius-control)] bg-surface-tint"></div>
        <div class="h-24 rounded-[var(--radius-control)] bg-surface-tint"></div>
      </div>
      <span class="sr-only">Loading handbook data</span>
    </div>`;
}

// ------------------------------------------------------------- theming

/**
 * Cytoscape paints into a canvas, so CSS custom properties never reach it.
 * Token values have to be read out of the document and handed over as plain
 * strings, then re-read whenever the colour scheme flips.
 */
function tokens() {
  const style = getComputedStyle(document.documentElement);
  const read = (name: string) => style.getPropertyValue(name).trim();
  return {
    surface: read("--surface"),
    surfaceTint: read("--surface-tint"),
    line: read("--line"),
    ink: read("--ink"),
    inkSoft: read("--ink-soft"),
    muted: read("--muted"),
    accent: read("--accent"),
    coreBg: read("--tag-core-bg"),
    coreFg: read("--tag-core-fg"),
    optionBg: read("--tag-option-bg"),
    optionFg: read("--tag-option-fg"),
    warnFg: read("--tag-warn-fg"),
  };
}

/**
 * A phone gets code-only nodes. A title inside the node is what forces it to be
 * 148px wide, and on a 390px canvas that width is paid twice: once for the node
 * and again for every node it pushes sideways. Codes alone keep the boxes small
 * enough that several fit on screen at a zoom where they can still be read, and
 * the title is one tap away in the detail sheet.
 */
function stylesheet(
  t: ReturnType<typeof tokens>,
  compact: boolean,
): cytoscape.StylesheetJson {
  return [
    {
      selector: "node",
      style: {
        shape: "round-rectangle",
        "corner-radius": 6,
        width: compact ? 84 : 148,
        height: compact ? 34 : 54,
        "background-color": t.surface,
        "border-width": 1,
        "border-color": t.line,
        label: compact ? "data(code)" : "data(label)",
        color: t.ink,
        "font-family": compact
          ? "Geist Mono Variable, monospace"
          : "Geist Variable, sans-serif",
        "font-size": compact ? 10 : 11,
        "text-wrap": "wrap",
        "text-max-width": compact ? "76px" : "130px",
        "text-valign": "center",
        "text-halign": "center",
        "line-height": 1.35,
      },
    },
    {
      selector: 'node[membership = "core"]',
      style: {
        "background-color": t.coreBg,
        "border-color": t.coreFg,
        color: t.ink,
      },
    },
    {
      selector: 'node[membership = "option"]',
      style: {
        "background-color": t.optionBg,
        "border-color": t.optionFg,
        color: t.ink,
      },
    },
    {
      selector: 'node[membership = "outside"]',
      style: {
        "background-color": t.surfaceTint,
        "border-color": t.line,
        color: t.inkSoft,
      },
    },
    {
      selector: "node:selected",
      style: { "border-width": 2, "border-color": t.accent, color: t.ink },
    },
    {
      selector: "node.dimmed",
      style: { opacity: 0.25 },
    },
    {
      selector: "edge",
      style: {
        width: 1.2,
        "line-color": t.muted,
        "target-arrow-color": t.muted,
        "target-arrow-shape": "triangle",
        "arrow-scale": 0.85,
        "curve-style": "bezier",
        opacity: 0.55,
      },
    },
    {
      selector: 'edge[kind = "coreq"]',
      style: { "line-style": "dashed", "target-arrow-shape": "none" },
    },
    // Advisable prior study is a recommendation, not a gate, so it is drawn
    // lighter than the rules that actually block enrolment.
    {
      selector: 'edge[kind = "advisable"]',
      style: {
        "line-style": "dotted",
        "target-arrow-shape": "vee",
        "line-color": t.inkSoft,
        "target-arrow-color": t.inkSoft,
        opacity: 0.35,
      },
    },
    {
      selector: "edge.highlight",
      style: {
        width: 2,
        "line-color": t.accent,
        "target-arrow-color": t.accent,
        opacity: 1,
      },
    },
    {
      selector: "edge.dimmed",
      style: { opacity: 0.08 },
    },
  ] as cytoscape.StylesheetJson;
}

// ---------------------------------------------------------------- state

const units = new Map<string, Unit>();
const majors: Major[] = [];
const detailCache = new Map<string, Record<string, UnitDetail>>();

let cy: cytoscape.Core | null = null;
let currentMajor: Major | null = null;
let membership = new Map<string, Membership>();

const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)");
const isDesktop = window.matchMedia("(min-width: 1024px)");

// ------------------------------------------------------------ graph model

/**
 * Resolve which units belong to the selected major and how they are taken.
 * A unit listed in more than one group is compulsory if any group requires it.
 */
function membershipFor(major: Major): Map<string, Membership> {
  const result = new Map<string, Membership>();
  for (const level of major.levels) {
    for (const group of level.groups) {
      for (const unit of group.units) {
        if (group.kind === "core" || !result.has(unit.code)) {
          result.set(unit.code, group.kind);
        }
      }
    }
  }
  return result;
}

function buildElements(
  major: Major,
  includeOutside: boolean,
  includeAdvisable: boolean,
) {
  membership = membershipFor(major);
  const visible = new Set(membership.keys());

  // One hop outward: prerequisites that sit outside the major are extremely
  // common (maths feeding computing, for example) and the graph is misleading
  // without them, so they are shown by default but visually demoted.
  if (includeOutside) {
    for (const code of [...visible]) {
      const unit = units.get(code);
      if (!unit) continue;
      for (const ref of [
        ...(unit.prereqUnits ?? []),
        ...(unit.coreqUnits ?? []),
        ...(includeAdvisable ? (unit.advisableUnits ?? []) : []),
      ]) {
        if (!visible.has(ref) && units.has(ref)) visible.add(ref);
      }
    }
  }

  const nodes: cytoscape.ElementDefinition[] = [];
  for (const code of visible) {
    const unit = units.get(code);
    if (!unit) continue;
    nodes.push({
      data: {
        id: code,
        code,
        label: `${code}\n${unit.title}`,
        membership: membership.get(code) ?? "outside",
      },
    });
  }

  const edges: cytoscape.ElementDefinition[] = [];
  const seen = new Set<string>();
  const drawn = new Set<string>();
  const addEdge = (
    from: string,
    to: string,
    kind: "prereq" | "coreq" | "advisable",
  ) => {
    if (!visible.has(from) || !visible.has(to) || from === to) return;
    const id = `${kind}:${from}->${to}`;
    if (seen.has(id)) return;
    // A unit is sometimes both a prerequisite and advisable prior study for the
    // same target. The binding rule wins; a second faint arrow beside it would
    // only read as two different relationships.
    if (drawn.has(`${from}->${to}`)) return;
    seen.add(id);
    drawn.add(`${from}->${to}`);
    edges.push({ data: { id, source: from, target: to, kind } });
  };

  for (const code of visible) {
    const unit = units.get(code);
    if (!unit) continue;
    for (const ref of unit.prereqUnits ?? []) addEdge(ref, code, "prereq");
    for (const ref of unit.coreqUnits ?? []) addEdge(ref, code, "coreq");
  }
  if (includeAdvisable) {
    for (const code of visible) {
      const unit = units.get(code);
      if (!unit) continue;
      for (const ref of unit.advisableUnits ?? []) addEdge(ref, code, "advisable");
    }
  }

  return { nodes, edges, visible };
}

/**
 * Report prerequisite cycles rather than hiding them.
 *
 * dagre breaks cycles internally so the layout never hangs, but a cycle always
 * means the handbook data is odd (usually a pair of units listing each other),
 * and silently drawing it as if it were a clean hierarchy would be misleading.
 */
function findCycles(edges: cytoscape.ElementDefinition[]): string[] {
  const adjacency = new Map<string, string[]>();
  for (const edge of edges) {
    if (edge.data.kind !== "prereq") continue;
    const from = edge.data.source as string;
    const list = adjacency.get(from) ?? [];
    list.push(edge.data.target as string);
    adjacency.set(from, list);
  }

  const state = new Map<string, 0 | 1 | 2>();
  const found: string[] = [];

  const walk = (node: string, path: string[]) => {
    state.set(node, 1);
    for (const next of adjacency.get(node) ?? []) {
      const mark = state.get(next) ?? 0;
      if (mark === 1) {
        found.push([...path.slice(path.indexOf(next)), next].join(" to "));
      } else if (mark === 0) {
        walk(next, [...path, next]);
      }
    }
    state.set(node, 2);
  };

  for (const node of adjacency.keys()) {
    if ((state.get(node) ?? 0) === 0) walk(node, [node]);
  }
  return found;
}

// ----------------------------------------------------------- graph render

function mount(container: HTMLElement) {
  cy?.destroy();
  cy = cytoscape({
    container,
    style: stylesheet(tokens(), !isDesktop.matches),
    minZoom: 0.08,
    maxZoom: 2.5,
    boxSelectionEnabled: false,
  });

  cy.on("tap", "node", (event) => {
    const code = event.target.id() as string;
    focusUnit(code);
  });

  cy.on("tap", (event) => {
    if (event.target === cy) {
      cy?.elements().removeClass("dimmed highlight");
      cy?.$(":selected").unselect();
      renderPlaceholder();
    }
  });

  return cy;
}

/**
 * dagre lays every disconnected component out in one long row, and most majors
 * are mostly disconnected: a handful of chains plus a dozen standalone units.
 * The result is a canvas ten times wider than it is tall, which fits to a zoom
 * where nothing is readable, worst of all on a phone. So each component is laid
 * out on its own and the results are packed into a block shaped like the
 * container. Returns the size of that block so the caller can compare rank
 * directions.
 */
function pack(rankDir: "TB" | "LR", aspect: number) {
  if (!cy) return { w: 1, h: 1 };

  const boxes = cy
    .elements()
    .components()
    .map((component) => {
      component
        .layout({
          name: "dagre",
          // @ts-expect-error dagre-specific options are not in the core layout type
          rankDir,
          nodeSep: isDesktop.matches ? 26 : 18,
          rankSep: isDesktop.matches ? 64 : 46,
          // dagre's minLen must be at least 1; passing 0 for co-requisites (to
          // keep the pair on one rank) corrupts ranking and throws once a major
          // has more than a couple of them. Co-requisites are drawn dashed
          // instead, which carries the same meaning without fighting the layout.
          animate: false,
          fit: false,
        })
        .run();
      const bb = component.boundingBox();
      return { nodes: component.nodes(), x1: bb.x1, y1: bb.y1, w: bb.w, h: bb.h };
    });

  const gap = isDesktop.matches ? 40 : 28;

  /** Shelf packing, tallest first, into rows no wider than `width`. */
  const shelve = (
    group: typeof boxes,
    width: number,
    originX: number,
    originY: number,
  ) => {
    let cursorX = 0;
    let cursorY = 0;
    let shelfHeight = 0;
    let used = 0;
    for (const box of group) {
      if (cursorX > 0 && cursorX + box.w > width) {
        cursorX = 0;
        cursorY += shelfHeight + gap;
        shelfHeight = 0;
      }
      const dx = originX + cursorX - box.x1;
      const dy = originY + cursorY - box.y1;
      box.nodes.forEach((node) => {
        const p = node.position();
        node.position({ x: p.x + dx, y: p.y + dy });
      });
      cursorX += box.w + gap;
      used = Math.max(used, cursorX - gap);
      shelfHeight = Math.max(shelfHeight, box.h);
    }
    return { w: used, h: cursorY + shelfHeight };
  };

  boxes.sort((a, b) => b.h * b.w - a.h * a.w);
  const [main, ...rest] = boxes;
  if (!rest.length) return { w: main.w, h: main.h };

  // The biggest connected chain sets the shape and everything else fills in
  // around it: beside the chain while there is room, underneath once there is
  // not. That is what keeps a mostly-disconnected major - and most of them are
  // mostly disconnected - from becoming one long row of orphan units.
  rest.sort((a, b) => b.h - a.h);
  const area =
    boxes.reduce((sum, box) => sum + (box.w + gap) * (box.h + gap), 0) * 1.15;
  const idealHeight = Math.sqrt(area / aspect);
  const idealWidth = area / idealHeight;
  const widestRest = rest.reduce((max, box) => Math.max(max, box.w), 0);
  const beside = idealWidth - main.w - gap;

  shelve([main], main.w, 0, 0);
  if (beside >= widestRest) {
    const block = shelve(rest, beside, main.w + gap, 0);
    return { w: main.w + gap + block.w, h: Math.max(main.h, block.h) };
  }
  const block = shelve(rest, Math.max(main.w, widestRest), 0, main.h + gap);
  return { w: Math.max(main.w, block.w), h: main.h + gap + block.h };
}

function runLayout() {
  if (!cy || cy.elements().empty()) return;

  // The canvas is mounted while its section is still hidden, and unhiding an
  // element fires no resize event, so cytoscape would otherwise pack and fit
  // against a stale (often zero) viewport.
  cy.resize();

  const container = cy.container();
  const aspect =
    container && container.clientHeight > 0
      ? container.clientWidth / container.clientHeight
      : 1.5;

  // Rank direction is the other half of the shape problem. An engineering major
  // is six ranks deep and forty units wide, so top-to-bottom draws a ribbon that
  // has to be zoomed out to nothing; the same graph laid left-to-right is much
  // closer to square. Neither reading is wrong - the arrow still runs from the
  // prerequisite - so both are tried and whichever ends up readable at a larger
  // zoom wins, which is the thing the reader actually feels.
  const readableAt = (box: { w: number; h: number }) =>
    Math.min(
      (container?.clientWidth ?? 900) / box.w,
      (container?.clientHeight ?? 600) / box.h,
    );

  const vertical = readableAt(pack("TB", aspect));
  const horizontal = readableAt(pack("LR", aspect));
  if (vertical >= horizontal) pack("TB", aspect);

  // Work out the resting viewport by moving there, then rewind and animate into
  // it, so the clamp below can be applied to a real zoom rather than guessed.
  const from = { zoom: cy.zoom(), pan: { ...cy.pan() } };
  cy.fit(undefined, isDesktop.matches ? 28 : 16);

  // A whole major fitted to a phone lands somewhere near 0.3, where no label is
  // readable. Below that floor the graph opens zoomed in at the top instead and
  // is panned from there; "Fit" is one tap away for the overview.
  const floor = 0.85;
  if (!isDesktop.matches && cy.zoom() < floor) {
    const bounds = cy.elements().boundingBox();
    cy.zoom(floor);
    cy.center();
    const dy = (cy.extent().y1 - bounds.y1 + 16) * cy.zoom();
    if (dy > 0) cy.panBy({ x: 0, y: dy });
  }

  if (!reducedMotion.matches) {
    const to = { zoom: cy.zoom(), pan: { ...cy.pan() } };
    cy.viewport(from);
    cy.animate({ zoom: to.zoom, pan: to.pan }, { duration: 240 });
  }
}

function render() {
  if (!currentMajor || !cy) return;

  const { nodes, edges } = buildElements(
    currentMajor,
    $outside.checked,
    $advisable.checked,
  );

  cy.elements().remove();
  cy.add([...nodes, ...edges]);
  runLayout();

  // Search suggestions follow whatever is on screen.
  $options.innerHTML = nodes
    .map(
      (n) =>
        `<option value="${esc(n.data.id as string)}">${esc(units.get(n.data.id as string)?.title ?? "")}</option>`,
    )
    .join("");

  const messages: string[] = [];
  if (edges.length === 0) {
    messages.push(
      `<strong class="font-medium text-ink">No prerequisite links to draw.</strong> The units in ${esc(currentMajor.name)} do not list each other as prerequisites. That is common: many majors gate on course enrolment or ATAR subjects rather than on other units. Select any unit to read its actual rule.`,
    );
  }
  const cycles = findCycles(edges);
  if (cycles.length) {
    messages.push(
      `The handbook lists a circular prerequisite: ${esc(cycles[0])}. The layout still draws it, but that chain cannot be taken in order as written.`,
    );
  }
  if (messages.length) note("info", messages.join('</p><p class="mt-2">'));
  else clearNote();

  renderCompact();
  renderPlaceholder();
}

// --------------------------------------------------------- detail panel

function tag(text: string, bg: string, fg: string) {
  return `<span class="tag" style="background:${bg};color:${fg}">${esc(text)}</span>`;
}

function renderPlaceholder() {
  const count = cy?.nodes().length ?? 0;
  $detail.innerHTML = `
    <p class="meta">Detail</p>
    <p class="mt-3 text-sm text-ink-soft">
      Select a unit to read its prerequisite rule as the handbook words it${
        count ? `. ${count} units are on screen` : ""
      }.
    </p>`;
}

async function loadDetail(code: string): Promise<UnitDetail | null> {
  const subject = code.slice(0, 4);
  if (!detailCache.has(subject)) {
    try {
      const res = await fetch(`${BASE}uwa-units/details/${subject}.json`);
      if (!res.ok) throw new Error(String(res.status));
      detailCache.set(subject, await res.json());
    } catch {
      detailCache.set(subject, {});
    }
  }
  return detailCache.get(subject)?.[code] ?? null;
}

/**
 * Rule text goes in verbatim, which is the whole point: the wording carries the
 * "and"/"or" structure that the arrows deliberately do not claim to encode.
 * Unit codes inside it are jumps to that node rather than links off the site.
 */
function ruleBlock(label: string, rule: Rule | undefined) {
  if (!rule?.html) return "";
  return `
    <div class="mt-4">
      <p class="meta">${esc(label)}</p>
      <div class="mt-1.5 text-sm leading-relaxed text-ink-soft
                  [&_a[href]]:text-accent [&_a[href]]:underline [&_a[href]]:underline-offset-2
                  [&_[data-unit]]:cursor-pointer [&_[data-unit]]:font-mono [&_[data-unit]]:text-xs
                  [&_[data-unit]]:text-accent [&_[data-unit]]:underline [&_[data-unit]]:underline-offset-2">${rule.html}</div>
    </div>`;
}

function focusUnit(code: string) {
  const unit = units.get(code);
  if (!unit || !cy) return;

  const node = cy.$id(code);
  if (node.nonempty()) {
    cy.$(":selected").unselect();
    node.select();

    // Dim everything except this unit's immediate chain, both directions.
    const chain = node.closedNeighborhood();
    cy.elements().addClass("dimmed");
    chain.removeClass("dimmed");
    cy.elements().removeClass("highlight");
    node.connectedEdges().addClass("highlight").removeClass("dimmed");

    // Reaching a unit through the search box or through a code inside a rule
    // can point at a node that is off screen, which looks like nothing happened.
    const view = cy.extent();
    const at = node.position();
    if (at.x < view.x1 || at.x > view.x2 || at.y < view.y1 || at.y > view.y2) {
      if (reducedMotion.matches) cy.center(node);
      else cy.animate({ center: { eles: node } }, { duration: 200 });
    }
  }

  const kind = membership.get(code);
  const badges = [
    kind === "core"
      ? tag("Compulsory", "var(--tag-core-bg)", "var(--tag-core-fg)")
      : "",
    kind === "option"
      ? tag("Option", "var(--tag-option-bg)", "var(--tag-option-fg)")
      : "",
    kind === undefined
      ? tag("Outside the major", "var(--surface-tint)", "var(--muted)")
      : "",
    unit.credits
      ? tag(`${unit.credits} points`, "var(--surface-tint)", "var(--ink-soft)")
      : "",
    ...unit.availability.map((a) =>
      tag(a, "var(--surface-tint)", "var(--ink-soft)"),
    ),
  ]
    .filter(Boolean)
    .join("");

  const dependents = [...units.values()]
    .filter((u) => (u.prereqUnits ?? []).includes(code))
    .map((u) => u.code)
    .sort();

  $detail.innerHTML = `
    <p class="meta">${esc(unit.code)}</p>
    <h2 class="display mt-1 text-xl">${esc(unit.title)}</h2>
    <div class="mt-3 flex flex-wrap gap-1.5">${badges}</div>

    ${ruleBlock("Prerequisites", unit.rules?.prerequisites)}
    ${ruleBlock("Co-requisites", unit.rules?.corequisites)}
    ${ruleBlock("Advisable prior study", unit.rules?.advisable)}
    ${ruleBlock("Incompatible with", unit.rules?.incompatibility)}
    ${ruleBlock("Approved quota", unit.rules?.quota)}
    ${
      unit.rules?.prerequisites
        ? ""
        : '<p class="mt-4 text-sm text-ink-soft">The handbook lists no prerequisites for this unit.</p>'
    }

    ${
      dependents.length
        ? `<div class="mt-4"><p class="meta">Leads to (${dependents.length})</p>
           <p class="mt-1.5 font-mono text-xs leading-relaxed text-ink-soft">${dependents.map(esc).join(", ")}</p></div>`
        : ""
    }

    <div id="detail-prose" class="mt-4"></div>

    <a href="${HANDBOOK}/unitdetails?code=${esc(unit.code)}" target="_blank" rel="noopener"
       class="mt-5 inline-flex items-center gap-1.5 text-sm text-accent underline underline-offset-2">
      Open in the handbook
    </a>`;

  // Unit codes inside a rule navigate within the graph. They are rendered from
  // handbook markup as plain <a> with no href, so they need explicit roles.
  $detail.querySelectorAll<HTMLElement>("[data-unit]").forEach((link) => {
    const target = link.dataset.unit;
    if (!target || !units.has(target)) return;
    link.setAttribute("role", "button");
    link.setAttribute("tabindex", "0");
    link.title = `Show ${target}`;
    const go = () => focusUnit(target);
    link.addEventListener("click", go);
    link.addEventListener("keydown", (event) => {
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();
        go();
      }
    });
  });

  void loadDetail(code).then((detail) => {
    const host = document.getElementById("detail-prose");
    if (!host || !detail?.description) return;
    host.innerHTML = `<p class="meta">Description</p>
      <div class="mt-1.5 text-sm leading-relaxed text-ink-soft">${detail.description}</div>`;
  });
}

// ------------------------------------------------------- compact fallback

function renderCompact() {
  if (!currentMajor) return;

  $compactList.innerHTML = currentMajor.levels
    .map((level) => {
      const groups = level.groups
        .map((group) => {
          const rows = group.units
            .map((entry) => {
              const unit = units.get(entry.code);
              const prereq = unit?.prereqUnits ?? [];
              const advisable = unit?.advisableUnits ?? [];
              return `
                <li class="rounded-[var(--radius-control)] border border-line bg-canvas p-3">
                  <p class="font-mono text-xs text-ink">${esc(entry.code)}</p>
                  <p class="mt-0.5 text-sm text-ink">${esc(unit?.title ?? "")}</p>
                  <p class="mt-1.5 text-xs text-ink-soft">${
                    prereq.length
                      ? `Needs ${prereq.map(esc).join(", ")}`
                      : "No unit prerequisites listed"
                  }</p>
                  ${
                    advisable.length
                      ? `<p class="mt-1 text-xs text-muted">Advisable first: ${advisable.map(esc).join(", ")}</p>`
                      : ""
                  }
                </li>`;
            })
            .join("");

          const badge =
            group.kind === "core"
              ? tag("Compulsory", "var(--tag-core-bg)", "var(--tag-core-fg)")
              : tag("Option", "var(--tag-option-bg)", "var(--tag-option-fg)");

          return `<div class="mt-4">
              <div class="flex flex-wrap items-center gap-2">${badge}<span class="meta">${esc(group.take)}</span></div>
              <ul class="mt-2 grid gap-2 sm:grid-cols-2">${rows}</ul>
            </div>`;
        })
        .join("");

      return `<section class="rounded-[var(--radius-card)] border border-line bg-surface p-4">
          <h2 class="display text-lg">${esc(level.level)}</h2>${groups}
        </section>`;
    })
    .join("");
}

// ------------------------------------------------------------- selection

function selectMajor(code: string) {
  const major = majors.find((m) => m.code === code);
  if (!major) return;

  if (major.kind === "disambiguation") {
    currentMajor = null;
    cy?.elements().remove();
    $workspace.classList.add("hidden");
    $compact.classList.add("hidden");
    renderPlaceholder();
    const links = major.variants
      .map((v) => {
        const target = majors.find((m) => m.code === v);
        return target
          ? `<button type="button" data-major="${esc(v)}" class="rounded-[var(--radius-control)] border border-line bg-canvas px-3 py-1.5 text-sm text-ink transition-colors hover:bg-surface-tint">${esc(target.name)} <span class="font-mono text-xs text-muted">${esc(v)}</span></button>`
          : "";
      })
      .filter(Boolean)
      .join("");
    note(
      "info",
      `<strong class="font-medium text-ink">${esc(major.name)} is split into separate majors</strong> depending on how much you have already studied. Pick the one that applies:<div class="mt-3 flex flex-wrap gap-2">${links}</div>`,
    );
    $status
      .querySelectorAll<HTMLButtonElement>("[data-major]")
      .forEach((button) => {
        button.addEventListener("click", () => {
          $major.value = button.dataset.major ?? "";
          selectMajor($major.value);
        });
      });
    return;
  }

  currentMajor = major;
  applyBreakpoint();
  render();
}

/**
 * The full-screen graph borrows the detail panel instead of duplicating it, so
 * a tap on a node still leads somewhere on a phone.
 */
function openOverlay() {
  $overlay.classList.remove("hidden");
  $overlay.classList.add("flex");
  el("overlay-detail").append($detail);
  mount(el("cy-mobile"));
  render();
}

function closeOverlay() {
  $overlay.classList.add("hidden");
  $overlay.classList.remove("flex");
  if ($detail.parentElement !== $workspace) $workspace.append($detail);
}

/** Desktop gets the canvas, small screens get the list until they ask for the graph. */
function applyBreakpoint() {
  if (!currentMajor) return;
  if (isDesktop.matches) {
    $workspace.classList.remove("hidden");
    $compact.classList.add("hidden");
    closeOverlay();
    if (!cy || cy.container() !== el("cy")) mount(el("cy"));
  } else {
    $workspace.classList.add("hidden");
    $compact.classList.remove("hidden");
  }
}

// ----------------------------------------------------------------- boot

async function main() {
  showSkeleton();

  let graphData: { units: Unit[]; year: string; scrapedAt: string };
  let majorData: { majors: Major[] };

  try {
    const [g, m] = await Promise.all([
      fetch(`${BASE}uwa-units/graph.json`),
      fetch(`${BASE}uwa-units/majors.json`),
    ]);
    if (!g.ok || !m.ok) throw new Error(`${g.status} ${m.status}`);
    graphData = await g.json();
    majorData = await m.json();
  } catch (error) {
    note(
      "error",
      `<strong class="font-medium text-ink">The handbook data did not load.</strong> ${esc(
        String(error),
      )}. Reload the page, or read the units directly at <a class="text-accent underline underline-offset-2" href="${HANDBOOK}">handbooks.uwa.edu.au</a>.`,
    );
    return;
  }

  for (const unit of graphData.units) units.set(unit.code, unit);
  majors.push(...majorData.majors);

  $provenance.textContent = `Handbook ${graphData.year}, read on ${graphData.scrapedAt}.`;

  $major.innerHTML = majors
    .map(
      (m) => `<option value="${esc(m.code)}">${esc(m.name || m.code)}</option>`,
    )
    .join("");

  const preferred =
    majors.find((m) => m.code === "MJD-CMPSC") ??
    majors.find((m) => m.kind === "major");
  if (!preferred) {
    note("error", "No majors were found in the data file. Re-run the scraper.");
    return;
  }

  $major.value = preferred.code;
  mount(el("cy"));
  selectMajor(preferred.code);

  // Events
  $major.addEventListener("change", () => selectMajor($major.value));
  $outside.addEventListener("change", () => render());
  $advisable.addEventListener("change", () => render());

  $search.addEventListener("change", () => {
    const code = $search.value.trim().toUpperCase();
    if (units.has(code)) focusUnit(code);
  });

  el<HTMLButtonElement>("fit").addEventListener("click", () => {
    cy?.fit(undefined, 28);
  });

  el<HTMLButtonElement>("fit-mobile").addEventListener("click", () => {
    cy?.fit(undefined, 20);
  });

  el<HTMLButtonElement>("open-graph").addEventListener("click", openOverlay);
  el<HTMLButtonElement>("close-graph").addEventListener("click", closeOverlay);

  document.addEventListener("keydown", (event) => {
    if (event.key === "Escape" && !$overlay.classList.contains("hidden")) {
      closeOverlay();
    }
  });

  isDesktop.addEventListener("change", () => {
    applyBreakpoint();
    if (isDesktop.matches) render();
  });

  // Re-read tokens when the colour scheme flips; the canvas cannot inherit them.
  window
    .matchMedia("(prefers-color-scheme: dark)")
    .addEventListener("change", () => {
      requestAnimationFrame(() =>
        cy?.style(stylesheet(tokens(), !isDesktop.matches)),
      );
    });
}

void main();
